### ISSUE TITLE
Create tag for 96256ab

### ISSUE THREAD

**Issue by killenb** [aquenos/ChimeraTK-ControlSystemAdapter-EPICS#4]
I just created a tag of the ChimeraTK EPICS IOC adapter which uses commit 96256ab of the device support adapter.
Can you please tag this version so the tag of the IOC adapter is referring to a tag of this project?

**Comment by smarsching** [comment]
Sure. Is the change that you made in 289f99081870f943a3b8272e1b6627c686b01741 for compatibility with version 3.0 of ChimeraTK Device Access? It would be useful to know this, so that I can add appropriate release notes.
I will probably tag this as version 2.0.0, considering that it will not be compatible with older version of ChimeraTK Device Access due to the changes in the API.

**Comment by killenb** [comment]
Sorry for the late reply. Yes, the changes are implementing the API adaptation for DeviceAccess 03.00.
We have not changed the major version of all downstream projects. DeviceAccess is just a dependency for them, and the API of the ControlSystemAdapter-EPICS has not changed. The EPICS-IOC adapter has only an increased patch version.
Maybe a minor version bump would be the right thing here, because the ControlSystemAdapter-EPICS is still 100 % source code compatible, yet it indicates that something has changed (you need a newer DeviceAccess version).

**Comment by smarsching** [comment]
Thank you for the explanation. I tagged the current version of the EPICS adapter as v1.1.0.
